<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\FoodCousins.Application\FoodCousins.Application.csproj" />
    <ProjectReference Include="..\FoodCousins.Infrastructure\FoodCousins.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
</Project>
